import type { JobPosting, JobWorkType } from '@/types/job';
import { JOB_WORK_TYPES, WORK_TYPE_LABELS } from '@/types/job';
import { CATEGORY_ITEM_COUNT } from '@/lib/list-page';

const JOBS: JobPosting[] = [
  {
    id: 'sample-1',
    title: '고객센터 상담원 정규직',
    companyName: '하모니커머스',
    workType: 'fulltime',
    payType: 'monthly',
    payLabel: '월급 280만원',
    location: '서울 구로구',
    summary: '자사몰 전화·채팅 문의 응대. 주 5일, 4대보험. 고객상담 경험자 우대.',
    createdAt: '2026-09-07',
  },
  {
    id: 'sample-8',
    title: '프론트엔드 개발자',
    companyName: '넥스트픽셀',
    workType: 'fulltime',
    payType: 'monthly',
    payLabel: '월급 420만원',
    location: '서울 서초구',
    summary: 'React 기반 서비스 화면 개발. 주 5일 하이브리드 근무, 경력 2년 이상.',
    createdAt: '2026-09-04',
  },
  {
    id: 'sample-9',
    title: '회계 담당자',
    companyName: '바른세무그룹',
    workType: 'fulltime',
    payType: 'monthly',
    payLabel: '월급 310만원',
    location: '서울 종로구',
    summary: '전표 처리와 월마감. 회계 프로그램 사용 가능하면 초보도 지원 가능합니다.',
    createdAt: '2026-09-01',
  },
  {
    id: 'sample-10',
    title: '물류센터 관리 정규직',
    companyName: '오름로지스',
    workType: 'fulltime',
    payType: 'monthly',
    payLabel: '월급 300만원',
    location: '경기 이천시',
    summary: '입고·출고 일정 관리. 주간 근무, 식대 지원. 물류 경험자 우대.',
    createdAt: '2026-08-28',
  },
  {
    id: 'sample-11',
    title: '콘텐츠 에디터',
    companyName: '콘텐츠랩365',
    workType: 'fulltime',
    payType: 'monthly',
    payLabel: '월급 290만원',
    location: '서울 마포구',
    summary: '뉴스레터와 블로그 원고 작성·교정. 주 5일, 유연출퇴근 가능.',
    createdAt: '2026-08-24',
  },
  {
    id: 'sample-12',
    title: '매장 매니저',
    companyName: '블루빈커피',
    workType: 'fulltime',
    payType: 'monthly',
    payLabel: '월급 270만원',
    location: '서울 마포구',
    summary: '홀 운영과 알바 스케줄 관리. 카페 근무 1년 이상이면 지원 가능합니다.',
    createdAt: '2026-08-20',
  },
  {
    id: 'sample-2',
    title: '마케팅 운영 계약직 (1년)',
    companyName: '라이트브랜딩',
    workType: 'contract',
    payType: 'monthly',
    payLabel: '월급 320만원',
    location: '서울 성동구',
    summary: 'SNS·상세페이지 운영. 계약 기간 1년, 평가 후 정규직 전환 가능.',
    createdAt: '2026-09-06',
  },
  {
    id: 'sample-13',
    title: 'HR 채용 운영 계약직',
    companyName: '피플온',
    workType: 'contract',
    payType: 'monthly',
    payLabel: '월급 300만원',
    location: '서울 강남구',
    summary: '공고 관리와 면접 일정 조율. 10개월 계약, 채용 업무 경험 우대.',
    createdAt: '2026-09-03',
  },
  {
    id: 'sample-14',
    title: '고객성공 매니저 계약직',
    companyName: '하모니커머스',
    workType: 'contract',
    payType: 'monthly',
    payLabel: '월급 330만원',
    location: '서울 구로구',
    summary: '입점 셀러 온보딩과 문의 대응. 1년 계약, 성과에 따라 연장합니다.',
    createdAt: '2026-08-30',
  },
  {
    id: 'sample-15',
    title: '영상 편집 계약직',
    companyName: '콘텐츠랩365',
    workType: 'contract',
    payType: 'monthly',
    payLabel: '월급 280만원',
    location: '재택 / 서울 강남구',
    summary: '유튜브 컷편집과 자막. 6개월 계약, 주 3일 재택 가능.',
    createdAt: '2026-08-26',
  },
  {
    id: 'sample-16',
    title: '데이터 라벨링 운영 계약직',
    companyName: '오름데이터',
    workType: 'contract',
    payType: 'monthly',
    payLabel: '월급 270만원',
    location: '경기 성남시',
    summary: '라벨러 일정 관리와 품질 검수. 8개월 프로젝트성 계약입니다.',
    createdAt: '2026-08-22',
  },
  {
    id: 'sample-17',
    title: '매장 오픈 지원 계약직',
    companyName: '블루빈커피',
    workType: 'contract',
    payType: 'monthly',
    payLabel: '월급 260만원',
    location: '서울 용산구',
    summary: '신규 매장 오픈 준비와 교육. 4개월 계약, 오픈 후 정규 전환 검토.',
    createdAt: '2026-08-18',
  },
  {
    id: 'sample-3',
    title: '서비스 기획 인턴',
    companyName: '콘텐츠랩365',
    workType: 'intern',
    payType: 'monthly',
    payLabel: '월급 220만원',
    location: '서울 강남구',
    summary: '6개월 인턴. 서비스 화면 정리와 사용자 인터뷰 보조. 포트폴리오 있으면 우대.',
    createdAt: '2026-09-06',
  },
  {
    id: 'sample-18',
    title: '마케팅 인턴',
    companyName: '라이트브랜딩',
    workType: 'intern',
    payType: 'monthly',
    payLabel: '월급 200만원',
    location: '서울 성동구',
    summary: 'SNS 초안 작성과 성과 정리. 3개월, 주 4일 근무도 협의 가능합니다.',
    createdAt: '2026-09-02',
  },
  {
    id: 'sample-19',
    title: '개발 인턴 (프론트)',
    companyName: '넥스트픽셀',
    workType: 'intern',
    payType: 'monthly',
    payLabel: '월급 230만원',
    location: '서울 서초구',
    summary: '사내 어드민 화면 수정. 6개월, HTML/CSS 기본만 되어도 지원 가능.',
    createdAt: '2026-08-29',
  },
  {
    id: 'sample-20',
    title: '디자인 인턴',
    companyName: '라이트브랜딩',
    workType: 'intern',
    payType: 'monthly',
    payLabel: '월급 210만원',
    location: '서울 성동구',
    summary: '상세페이지 시안 보조. 4개월, 피그마 사용 경험이면 충분합니다.',
    createdAt: '2026-08-25',
  },
  {
    id: 'sample-21',
    title: '인사총무 인턴',
    companyName: '피플온',
    workType: 'intern',
    payType: 'monthly',
    payLabel: '월급 200만원',
    location: '서울 강남구',
    summary: '문서 정리, 면접 안내, 비품 관리. 3개월 체험형 인턴입니다.',
    createdAt: '2026-08-21',
  },
  {
    id: 'sample-22',
    title: '콘텐츠 인턴',
    companyName: '하모니커머스',
    workType: 'intern',
    payType: 'monthly',
    payLabel: '월급 190만원',
    location: '서울 구로구',
    summary: '상품 후기 정리와 숏폼 대본 초안. 주 5일, 대학생 방학 인턴 환영.',
    createdAt: '2026-08-17',
  },
  {
    id: 'sample-4',
    title: '상세페이지 문구 작성',
    companyName: '라이트브랜딩',
    workType: 'freelance',
    payType: 'per_task',
    payLabel: '건당 25,000원',
    location: '재택',
    summary: '상품 특징을 보고 짧은 상세 문구를 작성하는 건별 일입니다. 포트폴리오 있으면 우대.',
    createdAt: '2026-09-05',
  },
  {
    id: 'sample-23',
    title: '유튜브 자막 검수',
    companyName: '콘텐츠랩365',
    workType: 'freelance',
    payType: 'per_task',
    payLabel: '영상 10분당 8,000원',
    location: '재택',
    summary: '자동 자막을 듣고 맞춤법·타이밍을 고치는 작업. 저녁·주말에도 가능합니다.',
    createdAt: '2026-09-02',
  },
  {
    id: 'sample-24',
    title: '로고 리터치',
    companyName: '피플온',
    workType: 'freelance',
    payType: 'per_task',
    payLabel: '건당 80,000원',
    location: '재택',
    summary: '기존 로고 색과 여백을 다듬는 단기 작업. 일러스트레이터 사용 가능자.',
    createdAt: '2026-08-28',
  },
  {
    id: 'sample-25',
    title: '번역 (한→영 상품명)',
    companyName: '하모니커머스',
    workType: 'freelance',
    payType: 'per_task',
    payLabel: '건당 15,000원',
    location: '재택',
    summary: '패션 상품명·옵션명을 자연스러운 영어로 옮기는 일. 건별 정산.',
    createdAt: '2026-08-23',
  },
  {
    id: 'sample-26',
    title: '엑셀 데이터 정리',
    companyName: '오름데이터',
    workType: 'freelance',
    payType: 'per_task',
    payLabel: '파일당 40,000원',
    location: '재택',
    summary: '중복 제거와 서식 통일. 함수 기본만 되면 가능합니다.',
    createdAt: '2026-08-19',
  },
  {
    id: 'sample-27',
    title: '제품 사진 보정',
    companyName: '블루빈커피',
    workType: 'freelance',
    payType: 'per_task',
    payLabel: '장당 7,000원',
    location: '재택',
    summary: '음료·디저트 컷 색감 보정. 라이트룸 또는 포토샵 사용.',
    createdAt: '2026-08-16',
  },
  {
    id: 'sample-5',
    title: '주말 카페 홀 알바',
    companyName: '블루빈커피',
    workType: 'parttime',
    payType: 'hourly',
    payLabel: '시급 11,000원',
    location: '서울 마포구',
    summary: '토·일 10:00~16:00. 간단한 음료 서빙과 홀 정리. 경력 무관.',
    createdAt: '2026-09-05',
  },
  {
    id: 'sample-28',
    title: '평일 오전 매장 알바',
    companyName: '블루빈커피',
    workType: 'parttime',
    payType: 'hourly',
    payLabel: '시급 11,500원',
    location: '서울 용산구',
    summary: '월~금 07:30~12:00. 오픈 준비와 간단한 제조. 출근 전 근무 환영.',
    createdAt: '2026-09-01',
  },
  {
    id: 'sample-29',
    title: '온라인 문의 응대 알바',
    companyName: '하모니커머스',
    workType: 'parttime',
    payType: 'hourly',
    payLabel: '시급 12,000원',
    location: '재택 (전국)',
    summary: '주 15시간부터. 카카오톡·이메일 응대, 육아와 병행하기 좋은 시간대입니다.',
    createdAt: '2026-08-27',
  },
  {
    id: 'sample-30',
    title: '도서관 열람실 보조',
    companyName: '피플온',
    workType: 'parttime',
    payType: 'hourly',
    payLabel: '시급 10,300원',
    location: '서울 노원구',
    summary: '평일 18:00~22:00. 좌석 안내와 자리 정리. 학생 지원 가능.',
    createdAt: '2026-08-23',
  },
  {
    id: 'sample-31',
    title: '물류 포장 알바',
    companyName: '오름로지스',
    workType: 'parttime',
    payType: 'hourly',
    payLabel: '시급 12,500원',
    location: '경기 이천시',
    summary: '주 3일 택. 13:00~18:00 포장·라벨 부착. 체력 부담 적은 작업입니다.',
    createdAt: '2026-08-19',
  },
  {
    id: 'sample-32',
    title: '학원 데스크 알바',
    companyName: '한빛학습센터',
    workType: 'parttime',
    payType: 'hourly',
    payLabel: '시급 11,000원',
    location: '서울 종로구',
    summary: '수강 안내와 전화 응대. 화·목·토 오후, 친절한 응대만 있으면 됩니다.',
    createdAt: '2026-08-15',
  },
  {
    id: 'sample-6',
    title: '사무보조 파견',
    companyName: '이벤트온',
    workType: 'dispatch',
    payType: 'monthly',
    payLabel: '월급 250만원',
    location: '서울 강남구',
    summary: '대기업 사무팀 파견. 문서 작성, 일정 관리, 방문객 안내. 파견 후 계약 연장 가능.',
    createdAt: '2026-09-04',
  },
  {
    id: 'sample-33',
    title: 'IT 헬프데스크 파견',
    companyName: '넥스트픽셀',
    workType: 'dispatch',
    payType: 'monthly',
    payLabel: '월급 270만원',
    location: '서울 서초구',
    summary: '사내 PC 장애 접수와 계정 발급. 1년 파견, 연장 가능성 높습니다.',
    createdAt: '2026-08-31',
  },
  {
    id: 'sample-34',
    title: '물류 현장 도급',
    companyName: '오름로지스',
    workType: 'dispatch',
    payType: 'monthly',
    payLabel: '월급 260만원',
    location: '경기 이천시',
    summary: '출고 피킹 도급. 야간 없음, 2교대 중 주간만 운영합니다.',
    createdAt: '2026-08-27',
  },
  {
    id: 'sample-35',
    title: '고객센터 파견 상담',
    companyName: '하모니커머스',
    workType: 'dispatch',
    payType: 'monthly',
    payLabel: '월급 255만원',
    location: '서울 구로구',
    summary: '인바운드 상담 파견. 교육 2주 제공, 경력 무관.',
    createdAt: '2026-08-22',
  },
  {
    id: 'sample-36',
    title: '전시 운영 도급',
    companyName: '이벤트온',
    workType: 'dispatch',
    payType: 'daily',
    payLabel: '일급 150,000원',
    location: '서울 강남구 COEX',
    summary: '부스 안내와 입장 관리. 기간 도급, 주말 포함 근무 가능자.',
    createdAt: '2026-08-18',
  },
  {
    id: 'sample-37',
    title: '회계 파견 보조',
    companyName: '바른세무그룹',
    workType: 'dispatch',
    payType: 'monthly',
    payLabel: '월급 265만원',
    location: '서울 종로구',
    summary: '전표 입력 파견. 6개월, 세무 프로그램 교육 후 투입합니다.',
    createdAt: '2026-08-14',
  },
  {
    id: 'sample-50',
    title: '보험 설계 위촉',
    companyName: '바른세무그룹',
    workType: 'commission',
    payType: 'per_task',
    payLabel: '건별 협의',
    location: '서울 종로구',
    summary: '개인·법인 보험 설계 위촉. 교육 제공, 기존 고객 유무는 무관합니다.',
    createdAt: '2026-09-03',
  },
  {
    id: 'sample-51',
    title: '산업기능요원 생산직',
    companyName: '오름로지스',
    workType: 'military',
    payType: 'monthly',
    payLabel: '월급 280만원',
    location: '경기 이천시',
    summary: '병역특례 산업기능요원. 주 5일 주간, 기숙사 가능합니다.',
    createdAt: '2026-09-02',
  },
  {
    id: 'sample-7',
    title: '자사몰 리뉴얼 프로젝트',
    companyName: '오름데이터',
    workType: 'project',
    payType: 'per_task',
    payLabel: '프로젝트 800만원',
    location: '재택 / 협의',
    summary: '3개월 쇼핑몰 개편. 프론트 화면과 결제 연동. 기간 내 산출물 기준으로 정산합니다.',
    createdAt: '2026-09-03',
  },
  {
    id: 'sample-38',
    title: '브랜드 홈페이지 제작',
    companyName: '라이트브랜딩',
    workType: 'project',
    payType: 'per_task',
    payLabel: '프로젝트 600만원',
    location: '재택 / 협의',
    summary: '소개 페이지 5면. 2개월, 디자인·퍼블리싱 가능 팀 또는 개인.',
    createdAt: '2026-08-30',
  },
  {
    id: 'sample-39',
    title: '채용 랜딩 캠페인',
    companyName: '피플온',
    workType: 'project',
    payType: 'per_task',
    payLabel: '프로젝트 450만원',
    location: '서울 강남구 / 재택',
    summary: '채용 마이크로사이트와 광고 소재. 6주 단기 프로젝트입니다.',
    createdAt: '2026-08-26',
  },
  {
    id: 'sample-40',
    title: '데이터 대시보드 구축',
    companyName: '오름데이터',
    workType: 'project',
    payType: 'per_task',
    payLabel: '프로젝트 900만원',
    location: '경기 성남시 / 재택',
    summary: '매출 지표 대시보드. 10주, SQL·시각화 경험 필수.',
    createdAt: '2026-08-21',
  },
  {
    id: 'sample-41',
    title: '앱 UI 개선 프로젝트',
    companyName: '넥스트픽셀',
    workType: 'project',
    payType: 'per_task',
    payLabel: '프로젝트 700만원',
    location: '서울 서초구',
    summary: '기존 앱 주요 화면 8개 개선. 2개월, 피그마 핸드오프까지.',
    createdAt: '2026-08-17',
  },
  {
    id: 'sample-42',
    title: '팝업스토어 운영 프로젝트',
    companyName: '이벤트온',
    workType: 'project',
    payType: 'per_task',
    payLabel: '프로젝트 500만원',
    location: '서울 성수동',
    summary: '3주 팝업 기획·현장 운영. 스태프 섭외와 일정 관리 포함.',
    createdAt: '2026-08-13',
  },
];

const EXTRA_JOB_TITLES: Record<JobWorkType, string[]> = {
  fulltime: ['영업 관리 정규직', '총무 담당 정규직', '품질관리 정규직', '구매 담당 정규직'],
  contract: ['브랜드 운영 계약직', 'CS 리드 계약직', '물류 기획 계약직', '교육 운영 계약직'],
  intern: ['영업 지원 인턴', '회계 보조 인턴', '물류 운영 인턴', '리서치 인턴'],
  freelance: ['카드뉴스 제작', '블로그 원고 작성', '상세페이지 디자인', '고객 후기 편집'],
  parttime: ['주말 매장 지원', '저녁 전화 상담', '오전 진열 보조', '주중 포장 알바'],
  dispatch: ['사무 보조 파견', '물류 검수 파견', '매장 진열 파견', '행사 안내 파견'],
  commission: ['학습지 교사 위촉', '부동산 중개 위촉', '방문판매 위촉', '상조 상담 위촉'],
  military: ['전문연구요원 채용', '병역특례 개발', '병역특례 품질관리', '산업기능요원 물류'],
  project: ['쇼핑몰 개편 프로젝트', '채용 사이트 제작', '브랜드 촬영 프로젝트', '프로모션 운영 프로젝트'],
};

function extraCreatedAt(index: number): string {
  const day = (index % 28) + 1;
  const month = index < 28 ? 8 : 7;
  return `2026-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

function padJobsPerType(jobs: JobPosting[], perType = CATEGORY_ITEM_COUNT): JobPosting[] {
  const extras: JobPosting[] = [];
  let seq = 100;

  for (const workType of JOB_WORK_TYPES) {
    const ofType = jobs.filter((job) => job.workType === workType);
    if (ofType.length === 0) continue;
    const titles = EXTRA_JOB_TITLES[workType];
    const needed = Math.max(0, perType - ofType.length);

    for (let index = 0; index < needed; index += 1) {
      const source = ofType[index % ofType.length];
      extras.push({
        ...source,
        id: `sample-extra-${seq}`,
        title: titles[index] ?? `${WORK_TYPE_LABELS[workType]} 채용 ${index + 1}`,
        createdAt: extraCreatedAt(index),
      });
      seq += 1;
    }
  }

  return [...jobs, ...extras];
}

export const SAMPLE_JOBS: JobPosting[] = padJobsPerType(JOBS).sort((a, b) =>
  b.createdAt.localeCompare(a.createdAt),
);
