import type { JobWorkType } from '@/types/job';
import { JOB_WORK_TYPES } from '@/types/job';
import { CATEGORY_ITEM_COUNT } from '@/lib/list-page';
import type { EducationLevel, TalentProfile } from '@/types/talent';

type TalentSeed = {
  name: string;
  headline: string;
  workType: JobWorkType;
  careerLabel: string;
  location: string;
  desiredPay: string;
  summary: string;
  experience: string;
  available: string;
  tags: string[];
  createdAt: string;
};

function sampleEducation(seed: TalentSeed): EducationLevel {
  if (seed.workType === 'intern' || seed.tags.includes('학생') || seed.tags.includes('학생환영')) {
    return '대학교 졸업 이상';
  }
  if (seed.careerLabel === '신입') return '대학교 졸업 이상';
  if (
    seed.headline.includes('물류') ||
    seed.headline.includes('포장') ||
    seed.headline.includes('피킹') ||
    seed.headline.includes('전시 운영') ||
    seed.headline.includes('카페') ||
    seed.headline.includes('오전 오픈')
  ) {
    return '고등학교 졸업 이상';
  }
  if (seed.headline.includes('데이터 대시보드')) return '석사 이상';
  const years = Number(seed.careerLabel.replace(/[^0-9]/g, ''));
  if (years > 0 && years <= 2) return '전문대학 졸업 이상';
  return '대학교 졸업 이상';
}

const SEEDS: TalentSeed[] = [
  {
    name: '김서연',
    headline: '고객센터 상담',
    workType: 'fulltime',
    careerLabel: '경력 4년',
    location: '서울 구로구',
    desiredPay: '월급 280만원',
    summary: '쇼핑몰 인바운드 상담과 채팅 응대를 담당했습니다. 응대 품질과 처리 속도를 함께 보는 일을 선호합니다.',
    experience: '하모니커머스 고객센터 3년, 이전 통신사 상담 1년. 월 평균 CSAT 4.7 유지.',
    available: '2주 후 출근 가능',
    tags: ['상담', 'CS', '채팅응대'],
    createdAt: '2026-09-07',
  },
  {
    name: '이준호',
    headline: '프론트엔드 개발',
    workType: 'fulltime',
    careerLabel: '경력 3년',
    location: '서울 서초구',
    desiredPay: '월급 420만원',
    summary: 'React로 서비스 화면을 만들고, 디자인 시스템 정리에도 참여했습니다. 하이브리드 근무를 희망합니다.',
    experience: '스타트업 웹 서비스 프론트 3년. 어드민·결제 화면 개선 경험.',
    available: '즉시 가능',
    tags: ['React', 'TypeScript', '하이브리드'],
    createdAt: '2026-09-04',
  },
  {
    name: '박민지',
    headline: '회계 담당',
    workType: 'fulltime',
    careerLabel: '경력 5년',
    location: '서울 종로구',
    desiredPay: '월급 310만원',
    summary: '전표 처리와 월마감, 부가세 신고 보조를 해 왔습니다. 정확한 마감을 중요하게 생각합니다.',
    experience: '세무법인 회계 보조 2년, 중소기업 경리 3년.',
    available: '한 달 후 가능',
    tags: ['회계', '전표', '월마감'],
    createdAt: '2026-09-01',
  },
  {
    name: '최현우',
    headline: '물류 관리',
    workType: 'fulltime',
    careerLabel: '경력 6년',
    location: '경기 이천시',
    desiredPay: '월급 300만원',
    summary: '입고·출고 일정과 재고 실사를 맡아 왔습니다. 주간 근무 정규직을 찾고 있습니다.',
    experience: '3PL 센터 현장 리더 4년, 이전 택배 허브 2년.',
    available: '즉시 가능',
    tags: ['물류', '재고', '주간'],
    createdAt: '2026-08-28',
  },
  {
    name: '정하은',
    headline: '콘텐츠 에디터',
    workType: 'fulltime',
    careerLabel: '경력 2년',
    location: '서울 마포구',
    desiredPay: '월급 290만원',
    summary: '뉴스레터와 블로그 원고를 쓰고 교정했습니다. 유연출퇴근이 가능한 곳을 선호합니다.',
    experience: '미디어 스타트업 에디터 2년. 주 3회 뉴스레터 발행.',
    available: '2주 후 가능',
    tags: ['글쓰기', '교정', '유연근무'],
    createdAt: '2026-08-24',
  },
  {
    name: '한도윤',
    headline: '매장 매니저',
    workType: 'fulltime',
    careerLabel: '경력 7년',
    location: '서울 마포구',
    desiredPay: '월급 270만원',
    summary: '카페 홀 운영과 파트타이머 스케줄을 관리했습니다. 매장 안정 운영이 강점입니다.',
    experience: '프랜차이즈 카페 점장 4년, 이전 바리스타 3년.',
    available: '즉시 가능',
    tags: ['매장', '스케줄', '교육'],
    createdAt: '2026-08-20',
  },
  {
    name: '오수빈',
    headline: '마케팅 운영',
    workType: 'contract',
    careerLabel: '경력 3년',
    location: '서울 성동구',
    desiredPay: '월급 320만원',
    summary: 'SNS와 상세페이지 운영을 1년 단위 계약으로 해 왔습니다. 전환 가능성이 있으면 더 좋습니다.',
    experience: '브랜드 마케팅 운영 3년. 월 콘텐츠 20건 이상 제작.',
    available: '즉시 가능',
    tags: ['SNS', '상세페이지', '계약직'],
    createdAt: '2026-09-06',
  },
  {
    name: '윤재민',
    headline: 'HR 채용 운영',
    workType: 'contract',
    careerLabel: '경력 4년',
    location: '서울 강남구',
    desiredPay: '월급 300만원',
    summary: '공고 관리와 면접 일정 조율을 담당했습니다. 10개월 이상 계약직을 찾고 있습니다.',
    experience: 'IT 기업 채용 운영 4년. 월 면접 40건 규모.',
    available: '2주 후 가능',
    tags: ['HR', '채용', '면접'],
    createdAt: '2026-09-03',
  },
  {
    name: '강지우',
    headline: '고객성공 매니저',
    workType: 'contract',
    careerLabel: '경력 2년',
    location: '서울 구로구',
    desiredPay: '월급 330만원',
    summary: '입점 셀러 온보딩과 문의 대응을 했습니다. 1년 계약 후 연장을 선호합니다.',
    experience: '커머스 CSM 2년. 온보딩 프로세스 문서화 경험.',
    available: '한 달 후 가능',
    tags: ['CSM', '온보딩', 'B2B'],
    createdAt: '2026-08-30',
  },
  {
    name: '배서준',
    headline: '영상 편집',
    workType: 'contract',
    careerLabel: '경력 5년',
    location: '재택 / 서울 강남구',
    desiredPay: '월급 280만원',
    summary: '유튜브 컷편집과 자막을 주로 했습니다. 주 3일 재택 가능한 계약을 원합니다.',
    experience: '콘텐츠 스튜디오 편집 5년. 주 4편 업로드 대응.',
    available: '즉시 가능',
    tags: ['프리미어', '자막', '재택'],
    createdAt: '2026-08-26',
  },
  {
    name: '신예린',
    headline: '데이터 라벨링 운영',
    workType: 'contract',
    careerLabel: '경력 3년',
    location: '경기 성남시',
    desiredPay: '월급 270만원',
    summary: '라벨러 일정과 품질 검수를 맡아 왔습니다. 프로젝트성 계약도 가능합니다.',
    experience: 'AI 데이터 팀 운영 3년. 검수 가이드 작성.',
    available: '2주 후 가능',
    tags: ['데이터', '검수', '운영'],
    createdAt: '2026-08-22',
  },
  {
    name: '조하린',
    headline: '매장 오픈 지원',
    workType: 'contract',
    careerLabel: '경력 4년',
    location: '서울 용산구',
    desiredPay: '월급 260만원',
    summary: '신규 매장 오픈 준비와 교육을 반복해 왔습니다. 단기 계약 후 전환도 괜찮습니다.',
    experience: '외식 브랜드 오픈 TF 4년. 연 3~4개 매장 오픈.',
    available: '즉시 가능',
    tags: ['오픈', '교육', '현장'],
    createdAt: '2026-08-18',
  },
  {
    name: '문채원',
    headline: '서비스 기획 인턴',
    workType: 'intern',
    careerLabel: '신입',
    location: '서울 강남구',
    desiredPay: '월급 220만원',
    summary: '화면 흐름 정리와 사용자 인터뷰 보조를 수업 프로젝트로 해 봤습니다. 6개월 인턴을 찾습니다.',
    experience: '대학 캡스톤에서 앱 와이어프레임 작성. 사용자 인터뷰 8명.',
    available: '즉시 가능',
    tags: ['기획', '인터뷰', '신입'],
    createdAt: '2026-09-06',
  },
  {
    name: '서민재',
    headline: '마케팅 인턴',
    workType: 'intern',
    careerLabel: '신입',
    location: '서울 성동구',
    desiredPay: '월급 200만원',
    summary: 'SNS 초안 작성과 간단한 성과 정리를 할 수 있습니다. 주 4일 근무도 가능합니다.',
    experience: '동아리 SNS 운영 1년. 캠퍼스 홍보 콘텐츠 제작.',
    available: '즉시 가능',
    tags: ['마케팅', 'SNS', '학생'],
    createdAt: '2026-09-02',
  },
  {
    name: '임하늘',
    headline: '프론트 개발 인턴',
    workType: 'intern',
    careerLabel: '신입',
    location: '서울 서초구',
    desiredPay: '월급 230만원',
    summary: 'HTML/CSS와 React 기초로 토이 프로젝트를 만들었습니다. 어드민 화면 수정을 배우고 싶습니다.',
    experience: '개인 포트폴리오 사이트 2개. 국비 프론트 과정 수료.',
    available: '2주 후 가능',
    tags: ['HTML', 'React', '인턴'],
    createdAt: '2026-08-29',
  },
  {
    name: '노은서',
    headline: '디자인 인턴',
    workType: 'intern',
    careerLabel: '신입',
    location: '서울 성동구',
    desiredPay: '월급 210만원',
    summary: '피그마로 상세페이지 시안을 그려 본 경험이 있습니다. 실무 피드백을 받으며 성장하고 싶습니다.',
    experience: '디자인 학원 포트폴리오 6개월. 상세페이지 시안 10장.',
    available: '즉시 가능',
    tags: ['피그마', '상세페이지', '인턴'],
    createdAt: '2026-08-25',
  },
  {
    name: '곽도현',
    headline: '인사총무 인턴',
    workType: 'intern',
    careerLabel: '신입',
    location: '서울 강남구',
    desiredPay: '월급 200만원',
    summary: '문서 정리와 방문객 안내를 꼼꼼히 하는 편입니다. 3개월 체험형 인턴을 희망합니다.',
    experience: '학교 행정 근로 2학기. 문서 스캔·일정 안내.',
    available: '즉시 가능',
    tags: ['총무', '문서', '안내'],
    createdAt: '2026-08-21',
  },
  {
    name: '황지아',
    headline: '콘텐츠 인턴',
    workType: 'intern',
    careerLabel: '신입',
    location: '서울 구로구',
    desiredPay: '월급 190만원',
    summary: '상품 후기 정리와 숏폼 대본 초안을 쓸 수 있습니다. 방학 기간 주 5일 근무 가능합니다.',
    experience: '캠퍼스 기자단 1년. 숏폼 대본 주 2편.',
    available: '즉시 가능',
    tags: ['콘텐츠', '숏폼', '학생환영'],
    createdAt: '2026-08-17',
  },
  {
    name: '유시온',
    headline: '상세페이지 카피',
    workType: 'freelance',
    careerLabel: '경력 3년',
    location: '재택',
    desiredPay: '건당 25,000원',
    summary: '상품 특징을 짧은 문구로 정리하는 건별 작업을 해 왔습니다. 포트폴리오 공유 가능합니다.',
    experience: '커머스 카피 프리랜서 3년. 월 평균 40건.',
    available: '즉시 가능',
    tags: ['카피', '재택', '건별'],
    createdAt: '2026-09-05',
  },
  {
    name: '장예준',
    headline: '자막 검수',
    workType: 'freelance',
    careerLabel: '경력 2년',
    location: '재택',
    desiredPay: '영상 10분당 8,000원',
    summary: '자동 자막의 맞춤법과 타이밍을 고치는 일을 저녁·주말에도 할 수 있습니다.',
    experience: '교육 채널 자막 검수 2년. 주 10시간 이상 가능.',
    available: '즉시 가능',
    tags: ['자막', '검수', '재택'],
    createdAt: '2026-09-02',
  },
  {
    name: '백소율',
    headline: '로고 리터치',
    workType: 'freelance',
    careerLabel: '경력 6년',
    location: '재택',
    desiredPay: '건당 80,000원',
    summary: '기존 로고의 색과 여백을 다듬는 단기 작업을 선호합니다. 일러스트레이터 사용 가능합니다.',
    experience: '브랜드 디자인 프리랜서 6년. BI 가이드 맞춤 수정.',
    available: '3일 내 착수',
    tags: ['일러스트레이터', 'BI', '건별'],
    createdAt: '2026-08-28',
  },
  {
    name: '남기태',
    headline: '영문 상품명 번역',
    workType: 'freelance',
    careerLabel: '경력 4년',
    location: '재택',
    desiredPay: '건당 15,000원',
    summary: '패션 상품명과 옵션명을 자연스러운 영어로 옮깁니다. 건별 정산을 원합니다.',
    experience: '커머스 번역 4년. 패션·리빙 카테고리 중심.',
    available: '즉시 가능',
    tags: ['번역', '영어', '재택'],
    createdAt: '2026-08-23',
  },
  {
    name: '고은별',
    headline: '엑셀 데이터 정리',
    workType: 'freelance',
    careerLabel: '경력 5년',
    location: '재택',
    desiredPay: '파일당 40,000원',
    summary: '중복 제거와 서식 통일을 빠르게 처리합니다. 기본 함수면 충분한 작업에 강합니다.',
    experience: '사무 프리랜서 5년. 대량 시트 정리·검증.',
    available: '즉시 가능',
    tags: ['엑셀', '정리', '재택'],
    createdAt: '2026-08-19',
  },
  {
    name: '안시후',
    headline: '제품 사진 보정',
    workType: 'freelance',
    careerLabel: '경력 3년',
    location: '재택',
    desiredPay: '장당 7,000원',
    summary: '음료·디저트 컷 색감 보정을 라이트룸으로 합니다. 장 단위 작업 가능합니다.',
    experience: '푸드 스튜디오 보정 3년. 주 200장 처리 경험.',
    available: '즉시 가능',
    tags: ['라이트룸', '보정', '건별'],
    createdAt: '2026-08-16',
  },
  {
    name: '홍나경',
    headline: '카페 홀 파트타임',
    workType: 'parttime',
    careerLabel: '경력 1년',
    location: '서울 마포구',
    desiredPay: '시급 11,000원',
    summary: '주말 오전~오후 홀 서빙이 가능합니다. 간단한 제조도 할 수 있습니다.',
    experience: '카페 홀 1년. 주말 고정 근무.',
    available: '이번 주말부터 가능',
    tags: ['주말', '홀', '시간제'],
    createdAt: '2026-09-05',
  },
  {
    name: '송지호',
    headline: '오전 오픈 파트타임',
    workType: 'parttime',
    careerLabel: '경력 2년',
    location: '서울 용산구',
    desiredPay: '시급 11,500원',
    summary: '평일 아침 오픈 근무를 선호합니다. 출근 전 짧은 타임이 좋습니다.',
    experience: '베이커리 오픈 2년. 07시 출근 익숙.',
    available: '즉시 가능',
    tags: ['오전', '오픈', '평일'],
    createdAt: '2026-09-01',
  },
  {
    name: '배수아',
    headline: '재택 문의 응대',
    workType: 'parttime',
    careerLabel: '경력 3년',
    location: '재택 (전국)',
    desiredPay: '시급 12,000원',
    summary: '주 15시간부터 카카오톡·이메일 응대가 가능합니다. 육아와 병행 가능한 시간대를 원합니다.',
    experience: '쇼핑몰 채팅 상담 3년. 재택 근무 2년.',
    available: '즉시 가능',
    tags: ['재택', '상담', '주 15시간'],
    createdAt: '2026-08-27',
  },
  {
    name: '권민서',
    headline: '열람실 보조',
    workType: 'parttime',
    careerLabel: '신입',
    location: '서울 노원구',
    desiredPay: '시급 10,300원',
    summary: '평일 저녁 좌석 안내와 자리 정리를 할 수 있습니다. 학생이라 저녁 타임이 맞습니다.',
    experience: '도서관 근로 한 학기. 열람실 안내.',
    available: '즉시 가능',
    tags: ['저녁', '안내', '학생'],
    createdAt: '2026-08-23',
  },
  {
    name: '도현민',
    headline: '물류 포장',
    workType: 'parttime',
    careerLabel: '경력 1년',
    location: '경기 이천시',
    desiredPay: '시급 12,500원',
    summary: '주 3일 오후 포장·라벨 부착이 가능합니다. 단순 반복 작업에 집중합니다.',
    experience: '물류센터 포장 1년. 피킹 보조.',
    available: '즉시 가능',
    tags: ['포장', '주 3일', '오후'],
    createdAt: '2026-08-19',
  },
  {
    name: '하윤서',
    headline: '학원 데스크',
    workType: 'parttime',
    careerLabel: '경력 2년',
    location: '서울 종로구',
    desiredPay: '시급 11,000원',
    summary: '화·목·토 오후 수강 안내와 전화 응대가 가능합니다. 친절한 응대를 강점으로 봅니다.',
    experience: '어학원 데스크 2년. 전화 상담·수납 보조.',
    available: '다음 주부터 가능',
    tags: ['데스크', '전화', '주 3일'],
    createdAt: '2026-08-15',
  },
  {
    name: '진서윤',
    headline: '사무보조 파견',
    workType: 'dispatch',
    careerLabel: '경력 3년',
    location: '서울 강남구',
    desiredPay: '월급 250만원',
    summary: '문서 작성과 일정 관리, 방문객 안내를 해 왔습니다. 파견 후 연장 가능한 곳을 찾습니다.',
    experience: '대기업 사무 파견 3년. 문서·일정·접대.',
    available: '2주 후 가능',
    tags: ['파견', '사무', '문서'],
    createdAt: '2026-09-04',
  },
  {
    name: '류태민',
    headline: 'IT 헬프데스크',
    workType: 'dispatch',
    careerLabel: '경력 4년',
    location: '서울 서초구',
    desiredPay: '월급 270만원',
    summary: '사내 PC 장애 접수와 계정 발급을 담당했습니다. 1년 이상 파견을 희망합니다.',
    experience: 'IT 아웃소싱 헬프데스크 4년. 티켓 처리.',
    available: '즉시 가능',
    tags: ['IT', '헬프데스크', '파견'],
    createdAt: '2026-08-31',
  },
  {
    name: '변지훈',
    headline: '물류 현장 도급',
    workType: 'dispatch',
    careerLabel: '경력 5년',
    location: '경기 이천시',
    desiredPay: '월급 260만원',
    summary: '출고 피킹 도급 현장을 주간으로만 해 왔습니다. 야간은 어렵습니다.',
    experience: '물류 도급 현장 5년. 주간 피킹 리더.',
    available: '즉시 가능',
    tags: ['도급', '피킹', '주간'],
    createdAt: '2026-08-27',
  },
  {
    name: '설아린',
    headline: '고객센터 파견 상담',
    workType: 'dispatch',
    careerLabel: '경력 2년',
    location: '서울 구로구',
    desiredPay: '월급 255만원',
    summary: '인바운드 상담 파견 경험이 있습니다. 교육 기간을 포함한 투입도 가능합니다.',
    experience: '카드사·쇼핑몰 상담 파견 2년.',
    available: '교육 후 즉시 투입',
    tags: ['상담', '파견', '인바운드'],
    createdAt: '2026-08-22',
  },
  {
    name: '마경호',
    headline: '전시 운영 도급',
    workType: 'dispatch',
    careerLabel: '경력 6년',
    location: '서울 강남구',
    desiredPay: '일급 150,000원',
    summary: '부스 안내와 입장 관리 도급을 반복해 왔습니다. 주말 포함 단기 투입이 가능합니다.',
    experience: '전시·컨벤션 운영 스태프 6년. COEX·SETEC.',
    available: '일정 맞춰 투입',
    tags: ['전시', '도급', '단기'],
    createdAt: '2026-08-18',
  },
  {
    name: '차지민',
    headline: '회계 파견 보조',
    workType: 'dispatch',
    careerLabel: '경력 3년',
    location: '서울 종로구',
    desiredPay: '월급 265만원',
    summary: '전표 입력 파견을 6개월 단위로 해 왔습니다. 세무 프로그램 교육 후 투입도 괜찮습니다.',
    experience: '세무 파견 보조 3년. 더존·수임처 전표.',
    available: '한 달 후 가능',
    tags: ['회계', '파견', '전표'],
    createdAt: '2026-08-14',
  },
  {
    name: '위지안',
    headline: '쇼핑몰 리뉴얼',
    workType: 'project',
    careerLabel: '경력 7년',
    location: '재택 / 협의',
    desiredPay: '프로젝트 800만원',
    summary: '자사몰 프론트와 결제 연동 개편을 프로젝트 단위로 해 왔습니다. 3개월 산출물 정산을 선호합니다.',
    experience: '커머스 구축 프리랜서 7년. Cafe24·독립몰.',
    available: '다음 달 착수',
    tags: ['웹', '결제', '3개월'],
    createdAt: '2026-09-03',
  },
  {
    name: '표세린',
    headline: '브랜드 홈페이지 제작',
    workType: 'project',
    careerLabel: '경력 5년',
    location: '재택 / 협의',
    desiredPay: '프로젝트 600만원',
    summary: '소개 페이지 디자인·퍼블리싱을 2개월 단위로 맡습니다. 팀 또는 혼자 진행 가능합니다.',
    experience: '에이전시·개인 프로젝트 5년. 기업 소개 사이트.',
    available: '2주 후 착수',
    tags: ['웹', '퍼블리싱', '2개월'],
    createdAt: '2026-08-30',
  },
  {
    name: '구하람',
    headline: '채용 랜딩 캠페인',
    workType: 'project',
    careerLabel: '경력 4년',
    location: '서울 강남구 / 재택',
    desiredPay: '프로젝트 450만원',
    summary: '채용 마이크로사이트와 광고 소재를 6주 안에 맞춘 경험이 있습니다.',
    experience: '퍼포먼스 디자인 4년. 채용·이벤트 랜딩.',
    available: '즉시 착수',
    tags: ['랜딩', '채용', '6주'],
    createdAt: '2026-08-26',
  },
  {
    name: '음재혁',
    headline: '데이터 대시보드',
    workType: 'project',
    careerLabel: '경력 8년',
    location: '경기 성남시 / 재택',
    desiredPay: '프로젝트 900만원',
    summary: '매출 지표 대시보드를 SQL과 시각화 툴로 구축합니다. 10주 전후 프로젝트를 선호합니다.',
    experience: '데이터 분석/BI 8년. Looker·Metabase.',
    available: '한 달 후 착수',
    tags: ['SQL', '대시보드', '10주'],
    createdAt: '2026-08-21',
  },
  {
    name: '탁소민',
    headline: '앱 UI 개선',
    workType: 'project',
    careerLabel: '경력 6년',
    location: '서울 서초구',
    desiredPay: '프로젝트 700만원',
    summary: '기존 앱 주요 화면을 개선하고 피그마 핸드오프까지 진행합니다. 2개월 단위가 적당합니다.',
    experience: '프로덕트 디자이너 6년. iOS/Android 개편.',
    available: '2주 후 착수',
    tags: ['UI', '피그마', '2개월'],
    createdAt: '2026-08-17',
  },
  {
    name: '봉우진',
    headline: '팝업스토어 운영',
    workType: 'project',
    careerLabel: '경력 5년',
    location: '서울 성수동',
    desiredPay: '프로젝트 500만원',
    summary: '3주 팝업의 기획과 현장 운영, 스태프 섭외까지 한 번에 맡습니다.',
    experience: '팝업·전시 운영 5년. 성수·한남 현장.',
    available: '일정 협의',
    tags: ['팝업', '운영', '3주'],
    createdAt: '2026-08-13',
  },
];

const EXTRA_TALENT_NAMES = [
  '김가온',
  '이하준',
  '박서율',
  '최은우',
  '정시우',
  '한유진',
  '오시아',
  '윤도하',
  '강태리',
  '배수빈',
  '신태윤',
  '문지호',
  '임나연',
  '노민재',
  '곽하린',
  '황도윤',
  '유세아',
  '장지안',
  '백하율',
  '남태오',
  '고은재',
  '안시윤',
  '홍지호',
  '송하람',
  '권도연',
  '하은성',
  '진서하',
  '류민호',
];

function extraCreatedAt(index: number): string {
  const day = (index % 28) + 1;
  const month = index < 28 ? 8 : 7;
  return `2026-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

function padTalentSeeds(seeds: TalentSeed[], perType = CATEGORY_ITEM_COUNT): TalentSeed[] {
  const extras: TalentSeed[] = [];
  let nameIndex = 0;

  for (const workType of JOB_WORK_TYPES) {
    const ofType = seeds.filter((item) => item.workType === workType);
    const needed = Math.max(0, perType - ofType.length);

    for (let index = 0; index < needed; index += 1) {
      const source = ofType[index % ofType.length];
      const baseName = EXTRA_TALENT_NAMES[nameIndex % EXTRA_TALENT_NAMES.length] ?? source.name;
      extras.push({
        ...source,
        name: `${baseName}${nameIndex + 1}`,
        createdAt: extraCreatedAt(index),
      });
      nameIndex += 1;
    }
  }

  return [...seeds, ...extras];
}

export const SAMPLE_TALENTS: TalentProfile[] = padTalentSeeds(SEEDS).map((item, index) => ({
  ...item,
  id: `talent-${index + 1}`,
  title: item.headline,
  education: sampleEducation(item),
  updatedAt: item.createdAt,
})).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
