import type { JobPosting } from '@/types/job';

export const SAMPLE_JOBS: JobPosting[] = [
  {
    id: 'sample-1',
    title: '온라인 쇼핑몰 고객문의 응대 (재택)',
    companyName: '하모니커머스',
    workType: 'remote',
    payType: 'hourly',
    payLabel: '시급 12,000원',
    location: '재택 (전국)',
    summary: '카카오톡·이메일 문의 응대. 주 15시간부터 가능, 육아와 병행하기 좋은 시간대입니다.',
    tags: ['재택', '주부환영', '주 15시간'],
    createdAt: '2026-09-05',
  },
  {
    id: 'sample-2',
    title: '주말 카페 홀 알바',
    companyName: '블루빈커피',
    workType: 'parttime',
    payType: 'hourly',
    payLabel: '시급 11,000원',
    location: '서울 마포구',
    summary: '토·일 10:00~16:00. 간단한 음료 서빙과 홀 정리. 경력 무관.',
    tags: ['알바', '주말', '시간제'],
    createdAt: '2026-09-04',
  },
  {
    id: 'sample-3',
    title: '상세페이지 문구 작성',
    companyName: '라이트브랜딩',
    workType: 'freelance',
    payType: 'per_task',
    payLabel: '건당 25,000원',
    location: '재택',
    summary: '상품 특징을 보고 짧은 상세 문구를 작성하는 건별 일입니다. 포트폴리오 있으면 우대.',
    tags: ['프리랜서', '재택', '건별'],
    createdAt: '2026-09-04',
  },
  {
    id: 'sample-4',
    title: '전시회 단기 안내데스크',
    companyName: '이벤트온',
    workType: 'short',
    payType: 'daily',
    payLabel: '일급 120,000원',
    location: '서울 강남구 COEX',
    summary: '9/12~9/14 3일간 방문객 안내. 밝은 인상과 기본 안내 경험이면 충분합니다.',
    tags: ['단기', '일급', '현장'],
    createdAt: '2026-09-03',
  },
  {
    id: 'sample-5',
    title: '데이터 입력 재택 파트타임',
    companyName: '오름데이터',
    workType: 'remote',
    payType: 'hourly',
    payLabel: '시급 11,500원',
    location: '재택 (전국)',
    summary: '엑셀 기본만 되면 가능. 평일 오전/오후 중 원하는 시간 4시간 근무.',
    tags: ['재택', '시간제', '초보가능'],
    createdAt: '2026-09-02',
  },
  {
    id: 'sample-6',
    title: '유튜브 자막 검수',
    companyName: '콘텐츠랩365',
    workType: 'freelance',
    payType: 'per_task',
    payLabel: '영상 10분당 8,000원',
    location: '재택',
    summary: '자동 자막을 듣고 맞춤법·타이밍을 고치는 작업. 저녁·주말에도 가능합니다.',
    tags: ['프리랜서', '재택', '건별'],
    createdAt: '2026-09-01',
  },
];
