import { getKoreaDateLocalToday } from '@/lib/datetime';
import type { CrawledJob } from '@/types/crawled-job';

const today = getKoreaDateLocalToday();
const yesterday = new Date();
yesterday.setDate(yesterday.getDate() - 1);
const yesterdayStr = getKoreaDateLocalToday(yesterday);

export const SAMPLE_CRAWLED_JOBS: CrawledJob[] = [
  {
    id: 'sample-samsung-1',
    sourceId: 'samsung-careers',
    sourceName: '삼성 채용',
    companyName: '삼성전자',
    title: '소프트웨어 엔지니어 (신입)',
    employmentTypes: ['신입'],
    roles: ['IT·개발'],
    regions: ['경기'],
    companySize: '대기업',
    deadline: '2026-12-31',
    applyUrl: 'https://www.samsungcareers.com/',
    description:
      '<p>삼성전자 DX부문 소프트웨어 엔지니어 신입 채용입니다.</p><ul><li>임베디드·플랫폼 개발</li><li>4년제 졸업(예정) 이상</li></ul>',
    status: 'active',
    crawledAt: `${today}T08:00:00.000Z`,
    createdAt: `${today}T08:00:00.000Z`,
    closedAt: null,
  },
  {
    id: 'sample-hyundai-1',
    sourceId: 'hyundai-careers',
    sourceName: '현대자동차 채용',
    companyName: '현대자동차',
    title: '자율주행 AI 연구원',
    employmentTypes: ['경력'],
    roles: ['연구·개발', 'IT·개발'],
    regions: ['서울'],
    companySize: '대기업',
    deadline: '2026-11-15',
    applyUrl: 'https://talent.hyundai.com/',
    description: '<p>자율주행 인지·제어 AI 연구 및 상용화를 담당합니다.</p>',
    status: 'active',
    crawledAt: `${today}T08:05:00.000Z`,
    createdAt: `${today}T08:05:00.000Z`,
    closedAt: null,
  },
  {
    id: 'sample-naver-1',
    sourceId: 'naver-careers',
    sourceName: '네이버 채용',
    companyName: '네이버',
    title: '프론트엔드 개발자',
    employmentTypes: ['경력'],
    roles: ['IT·개발'],
    regions: ['경기', '재택'],
    companySize: '대기업',
    deadline: null,
    applyUrl: 'https://recruit.navercorp.com/',
    description: '<p>네이버 주요 서비스 프론트엔드 개발</p>',
    status: 'active',
    crawledAt: `${yesterdayStr}T12:00:00.000Z`,
    createdAt: `${yesterdayStr}T12:00:00.000Z`,
    closedAt: null,
  },
  {
    id: 'sample-kakao-1',
    sourceId: 'kakao-careers',
    sourceName: '카카오 채용',
    companyName: '카카오',
    title: '서비스 기획자 (경력)',
    employmentTypes: ['경력'],
    roles: ['기획·PM'],
    regions: ['서울'],
    companySize: '대기업',
    deadline: '2026-10-20',
    applyUrl: 'https://careers.kakao.com/',
    description: '<p>카카오톡·메신저 서비스 기획</p>',
    status: 'active',
    crawledAt: `${yesterdayStr}T18:00:00.000Z`,
    createdAt: `${yesterdayStr}T18:00:00.000Z`,
    closedAt: null,
  },
  {
    id: 'sample-intern-1',
    sourceId: 'lg-careers',
    sourceName: 'LG 채용',
    companyName: 'LG전자',
    title: '글로벌 마케팅 인턴',
    employmentTypes: ['인턴'],
    roles: ['마케팅·광고'],
    regions: ['서울'],
    companySize: '대기업',
    deadline: '2026-10-31',
    applyUrl: 'https://careers.lg.com/',
    description: '<p>글로벌 마케팅 인턴십 프로그램</p>',
    status: 'active',
    crawledAt: `${today}T08:10:00.000Z`,
    createdAt: `${today}T08:10:00.000Z`,
    closedAt: null,
  },
];
